// <auto-generated />
using System;
using CarManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarManager.Migrations
{
    [DbContext(typeof(CarManageDbContext))]
    [Migration("20220909015022_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CarManager.Models.TuyenDuong", b =>
                {
                    b.Property<int?>("TuyenDuongId")
                        .HasColumnType("int");

                    b.Property<string>("Nhaxe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuangDuong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Thoigian")
                        .HasColumnType("datetime2");

                    b.HasKey("TuyenDuongId");

                    b.ToTable("tb_Tuyenduong");
                });

            modelBuilder.Entity("CarManager.Models.Xe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BienSo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaiTrong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenXe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TuyenDuongId")
                        .HasColumnType("int");

                    b.Property<string>("XeId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TuyenDuongId");

                    b.ToTable("tb_Xe");
                });

            modelBuilder.Entity("CarManager.Models.Xe", b =>
                {
                    b.HasOne("CarManager.Models.TuyenDuong", "TuyenDuong")
                        .WithMany()
                        .HasForeignKey("TuyenDuongId");

                    b.Navigation("TuyenDuong");
                });
#pragma warning restore 612, 618
        }
    }
}
